"""2023-12-24-1

Revision ID: 0738c00ad371
Revises: d4630fea7aed
Create Date: 2023-12-24 20:13:46.656684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0738c00ad371'
down_revision = 'd4630fea7aed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name_index', 'games', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_index', table_name='games')
    # ### end Alembic commands ###
