"""2023-12-16-1

Revision ID: 18987ced88ac
Revises: e7c07143c347
Create Date: 2023-12-16 20:18:37.690514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18987ced88ac'
down_revision = 'e7c07143c347'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK__games__series_id__4CA06362', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'series', ['series_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('FK__games__series_id__4CA06362', 'games', 'series', ['series_id'], ['id'])
    # ### end Alembic commands ###
