"""2023-12-17-1

Revision ID: d4630fea7aed
Revises: 18987ced88ac
Create Date: 2023-12-17 00:38:54.103351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4630fea7aed'
down_revision = '18987ced88ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('reviews', sa.Column('update_reason', sa.String(length=64), nullable=True))
    op.add_column('reviews', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'users', ['updated_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'updated_by_id')
    op.drop_column('reviews', 'update_reason')
    op.drop_column('reviews', 'updated_at')
    # ### end Alembic commands ###
